/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.OrderBLL;
import BLL.VegetableBLL;
import DTO.Orders;
import DTO.Vegetable;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class SelectVegetable extends javax.swing.JFrame {
    private DefaultTableModel tblvegetablemodel;
    /**
     * Creates new form SelectVegetable
     */
    public SelectVegetable() {
        initComponents();
        initTableVegetables();
        loadDataToTableVegetables();
        loadDataToCbb();
        this.setLocationRelativeTo(null);
    }
    private void initTableVegetables() {
        tblvegetablemodel = new DefaultTableModel();
        tblvegetablemodel.setColumnIdentifiers(new String[] {"VegetableID","Vegetable Name","Category","Unit",
            "Amount","Price"});
        tblvegetable.setModel(tblvegetablemodel);
    }
    private void loadDataToTableVegetables() {
        try {
            VegetableBLL bll = new  VegetableBLL();
            List<Vegetable> list = bll.LoadVegetables(WIDTH);
            tblvegetablemodel.setRowCount(0);
            for (Vegetable it : list) {
                tblvegetablemodel.addRow(new Object[]{
                    it.getVegetableID(),  it.getVegetable_Name(),it.getCategory().getName(),
                    it.getUnit(), it.getAmount(), it.getPrice()
              });
            }
            tblvegetablemodel.fireTableDataChanged();
        } catch (Exception e) {
        }
    }
     private void loadDataToCbb(){
         try {
            VegetableBLL bll = new  VegetableBLL();
            List<Vegetable> list = bll.LoadVegetables(WIDTH);
            List<String> temp1 = new ArrayList<String>();
            List<String> temp2 = new ArrayList<String>();
            List<String> listcate_name = new ArrayList<String>();
            List<String> listunit = new ArrayList<String>();
            cbbcategory.addItem("null");
            cbbunit.addItem("null");
            cbbamount.addItem("null");
            cbbprice.addItem("null");
            for (Vegetable vg : list) {
                temp1.add(vg.getCategory().getName());
                temp2.add(vg.getUnit());
            }
            for(String cate_name : temp1 ){
                if(!listcate_name.contains(cate_name)){
                    listcate_name.add(cate_name);
                    cbbcategory.addItem(cate_name);
                }
            }
            for(String unit : temp2 ){
                if(!listunit.contains(unit)){
                    listunit.add(unit);
                    cbbunit.addItem(unit);
                }
            }
            cbbamount.addItem("Amount <30");
            cbbamount.addItem("Amount >30");
            cbbamount.addItem("Amount >30");
            cbbamount.addItem("30<=Amount<=100");
            cbbamount.addItem("Amount >100");
            cbbprice.addItem("Descending");
            cbbprice.addItem("Ascending");
        } catch (Exception e) {
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblvegetable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbbcategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbbunit = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbbamount = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbbprice = new javax.swing.JComboBox<>();
        btnfilter = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        txtkeyword = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setText("SEARCH: Vegetable");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Key word:");

        tblvegetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblvegetable);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter by", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Category name:");

        cbbcategory.setFont(new java.awt.Font("SansSerif", 0, 12));
        cbbcategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbcategoryItemStateChanged(evt);
            }
        });
        cbbcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbcategoryActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Unit:");

        cbbunit.setFont(new java.awt.Font("SansSerif", 0, 12));
        cbbunit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbunitItemStateChanged(evt);
            }
        });
        cbbunit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbunitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("Amount:");

        cbbamount.setFont(new java.awt.Font("SansSerif", 0, 12));
        cbbamount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbamountItemStateChanged(evt);
            }
        });
        cbbamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbamountActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setText("Price:");

        cbbprice.setFont(new java.awt.Font("SansSerif", 0, 12));
        cbbprice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbpriceItemStateChanged(evt);
            }
        });
        cbbprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbpriceActionPerformed(evt);
            }
        });

        btnfilter.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnfilter.setText("Filter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(71, 71, 71)
                        .addComponent(cbbprice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(btnfilter, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbamount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbunit, 0, 177, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbbunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cbbamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cbbprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnfilter)
                .addContainerGap())
        );

        btnsearch.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnsearch.setText("Search");

        txtkeyword.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtkeyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkeywordKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtkeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsearch)
                        .addGap(18, 18, 18))
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(btnsearch)
                    .addComponent(txtkeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbcategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbcategoryItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbcategoryItemStateChanged

    private void cbbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbcategoryActionPerformed

    private void cbbunitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbunitItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbunitItemStateChanged

    private void cbbunitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbunitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbunitActionPerformed

    private void cbbamountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbamountItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbamountItemStateChanged

    private void cbbamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbamountActionPerformed

    private void cbbpriceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbpriceItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbpriceItemStateChanged

    private void cbbpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbpriceActionPerformed

    private void txtkeywordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkeywordKeyReleased
        
    }//GEN-LAST:event_txtkeywordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectVegetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectVegetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectVegetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectVegetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectVegetable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfilter;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox<String> cbbamount;
    private javax.swing.JComboBox<String> cbbcategory;
    private javax.swing.JComboBox<String> cbbprice;
    private javax.swing.JComboBox<String> cbbunit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblvegetable;
    private javax.swing.JTextField txtkeyword;
    // End of variables declaration//GEN-END:variables
}
